name: MLflow Workflow CI - Fanya (Direct Training Mode)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # === [1] Checkout repository ===
      - name: Checkout repository
        uses: actions/checkout@v3

      # === [2] Setup Python ===
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # === [3] Install dependencies ===
      - name: Install dependencies
        run: |
          echo "📦 Menginstal dependensi..."
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas dagshub docker

      # === [4] Bersihkan artefak lama ===
      - name: Clean previous MLflow runs
        run: |
          echo "🧹 Menghapus folder MLflow lama..."
          rm -rf mlruns || true

      # === [5] Jalankan training langsung ===
- name: Run MLflow training (direct mode)
  run: |
    echo "🚀 Menjalankan training langsung via MLProject..."
    cd MLProject
    export MLFLOW_TRACKING_URI="file://$(pwd)/mlruns"
    python modelling.py

# === [6] Dapatkan run_id terbaru ===
- name: Get latest MLflow run_id
  id: get_run
  run: |
    cd MLProject
    echo "🔍 Mendeteksi run_id terbaru..."
    if [ ! -d "mlruns/0" ]; then
      echo "❌ Folder mlruns belum terbentuk. Cek apakah training berhasil."
      exit 1
    fi
    RUN_ID=$(basename $(ls -td mlruns/0/*/ | head -1))
    echo "✅ Run ID ditemukan: $RUN_ID"
    echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT


      # === [7] Upload artefak ===
      - name: Upload model artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: fanya-mlflow-model
          path: mlruns/

      # === [8] Build Docker ===
      - name: Build Docker model
        run: |
          echo "🐳 Membangun Docker image dari model MLflow..."
          mlflow models build-docker -m "mlruns/0/${{ steps.get_run.outputs.run_id }}/artifacts/model" -n fanya-mlflow-model

      # === [9] Login ke Docker Hub ===
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # === [10] Push Docker image ===
      - name: Tag and Push Docker image
        run: |
          echo "📦 Push image ke Docker Hub..."
          docker tag fanya-mlflow-model:latest ${{ secrets.DOCKER_USERNAME }}/fanya-mlflow-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fanya-mlflow-model:latest

      # === [11] Selesai ===
      - name: Complete job
        run: echo "✅ Workflow CI selesai tanpa error!"
